name: stadium_app_task
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # design
  shimmer: ^3.0.0
  enefty_icons: ^1.0.7
  # device_preview: ^1.2.0
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3

  # storage
  shared_preferences: ^2.3.2

  # dio
  dio: ^5.5.0+1

  # map
  latlong2: ^0.9.0
  geolocator: ^11.1.0
  yandex_mapkit: ^4.1.0

  # route
  go_router: ^14.2.3

  # statemanagment
  flutter_riverpod: ^2.5.1

  # flutter_svg
  flutter_svg: ^2.0.10+1

  # check connection
  connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/img/

  fonts:
    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
